[alembic]
script_location = %(here)s/backend/plango/migrations
path_separator = newline
prepend_sys_path =
    %(here)s/backend
    %(here)s/vendor/plango_harness/backend
version_locations =
    %(here)s/vendor/plango_harness/backend/plango_harness/persistence/migrations/versions
    %(here)s/backend/plango/migrations/versions
